select * from Personnes;
select * from Dossiers;
select * from Voyages;
select * from Destinations;
select * from Agences;
select * from AssurDoss;
select * from ParticipDoss;
select * from Assurances;
select * from Authentifications;